"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Pose(object):

    __slots__ = ["position", "is_correct"]

    __typenames__ = ["double", "boolean"]

    __dimensions__ = [[3], None]

    def __init__(self):
        self.position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.is_correct = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(Pose._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack(">b", self.is_correct))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Pose._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Pose._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Pose()
        self.position = struct.unpack('>3d', buf.read(24))
        self.is_correct = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Pose in parents: return 0
        tmphash = (0xe1553bf788b64978) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Pose._packed_fingerprint is None:
            Pose._packed_fingerprint = struct.pack(">Q", Pose._get_hash_recursive([]))
        return Pose._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Pose._get_packed_fingerprint())[0]

