"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct
import numpy as np

class RGBCamera(object):

    __slots__ = ["timestamp", "width", "height", "channels", "image"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t", "int16_t"]

    __dimensions__ = [None, None, None, None, ["height", "width", "channels"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.width = 0
        """ LCM Type: int32_t """
        self.height = 0
        """ LCM Type: int32_t """
        self.channels = 0
        """ LCM Type: int32_t """
        self.image = []
        """ LCM Type: int16_t[height][width][channels] """

    def encode(self):
        buf = BytesIO()
        buf.write(RGBCamera._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiii", self.timestamp, self.width, self.height, self.channels))
        for i0 in range(self.height):
            for i1 in range(self.width):
                buf.write(struct.pack('>%dh' % self.channels, *self.image[i0][i1][:self.channels]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != RGBCamera._get_packed_fingerprint():
            raise ValueError("Decode error")
        return RGBCamera._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = RGBCamera()

        # Header: 8 (timestamp) + 4x3 (width, height, channels) = 20 bytes
        self.timestamp, self.width, self.height, self.channels = struct.unpack(">qiii", buf.read(20))

        num_pixels = self.width * self.height * self.channels
        image_bytes = buf.read(num_pixels * 2)  # 2 bytes per int16

        # Read all data at once into a NumPy array
        image = np.frombuffer(image_bytes, dtype='>i2')  # big-endian int16
        image = image.reshape((self.height, self.width, self.channels))

        self.image = image
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if RGBCamera in parents: return 0
        tmphash = (0x12773a907ecce8a3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if RGBCamera._packed_fingerprint is None:
            RGBCamera._packed_fingerprint = struct.pack(">Q", RGBCamera._get_hash_recursive([]))
        return RGBCamera._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", RGBCamera._get_packed_fingerprint())[0]

