"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class VelocitySensor(object):

    __slots__ = ["timestamp", "velocity"]

    __typenames__ = ["int64_t", "float"]

    __dimensions__ = [None, [3]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.velocity = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(VelocitySensor._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3f', *self.velocity[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != VelocitySensor._get_packed_fingerprint():
            raise ValueError("Decode error")
        return VelocitySensor._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = VelocitySensor()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.velocity = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if VelocitySensor in parents: return 0
        tmphash = (0x13111cc3baf33cae) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if VelocitySensor._packed_fingerprint is None:
            VelocitySensor._packed_fingerprint = struct.pack(">Q", VelocitySensor._get_hash_recursive([]))
        return VelocitySensor._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", VelocitySensor._get_packed_fingerprint())[0]

